# Generated by Django 3.2.1 on 2021-05-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodkart', '0005_auto_20210510_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
