# Generated by Django 3.2.1 on 2021-05-12 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodkart', '0010_addresses_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addresses',
            name='address',
        ),
    ]
