# Generated by Django 3.2.1 on 2021-06-10 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodkart', '0013_orders_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='exec_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user3', to=settings.AUTH_USER_MODEL),
        ),
    ]
