# Generated by Django 3.2.1 on 2021-06-13 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodkart', '0014_alter_orders_exec_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='foodkart.restaurant'),
        ),
    ]
